<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGFIqavV\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGFIqavV/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGFIqavV.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGFIqavV\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGFIqavV\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GFIqavV',
    'container.build_id' => 'cdd6d996',
    'container.build_time' => 1563968844,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGFIqavV');
