<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM5rKUyn\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM5rKUyn/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM5rKUyn.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM5rKUyn\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerM5rKUyn\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'M5rKUyn',
    'container.build_id' => '56e588d3',
    'container.build_time' => 1563997121,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM5rKUyn');
