<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL7huyV8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL7huyV8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL7huyV8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL7huyV8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerL7huyV8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'L7huyV8',
    'container.build_id' => '4ef23ac8',
    'container.build_time' => 1563915414,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL7huyV8');
