<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.kxoZs2X' shared service.

return $this->privates['.service_locator.kxoZs2X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\UserController::ajoutPartenaire' => ['privates', '.service_locator.yYhyP3Y', 'get_ServiceLocator_YYhyP3YService.php', true],
    'App\\Controller\\UserController:ajoutPartenaire' => ['privates', '.service_locator.yYhyP3Y', 'get_ServiceLocator_YYhyP3YService.php', true],
], [
    'App\\Controller\\UserController::ajoutPartenaire' => '?',
    'App\\Controller\\UserController:ajoutPartenaire' => '?',
]);
